### ISSUE TITLE
How to step through Spec.v in CoqIDE?

### ISSUE THREAD

**Issue by lf94** [clarus/coq-chick-blog#11]
Your project is extremely interesting to me, as the aspects it touches on are exactly what I want to learn with using Coq.

Right now I'm trying to step through Spec.v using CoqIDE, but it can't find Computation.vos. Why, I have no clue, because I've compiled the source files using `configure.sh && make`.

Here is a screenshot:

![1598202616](https://user-images.githubusercontent.com/547923/90984338-3bacbd00-e542-11ea-941b-7fe7d28077bc.png)

In your README it would be nice to mention you need to download the other projects you've written (coq-moment, coq-list-strings, etc) :slightly_smiling_face:  I can make a PR for this.

All in all, awesome work. I think it's a fantastic piece to learn from. How long have you been using Coq before you wrote this?

**Comment by clarus** [comment]
Hi,

Thanks for the kind words! Maybe this is because you need to run `coqide` with the `-R src ChickBlog` as in the file `Make`.

Indeed there are no mentions of dependencies to download. A possibility is also to run:
```
opam install .
```
from the project  folder to compile it and install the dependencies. Thanks if you can make a PR!

I have been doing this project as part of my PhD. I have stumbled upon Coq quite a long ago (2006) but have not practiced Coq continuously.

**Comment by lf94** [comment]
Ah ok. I'll do that then.

If you are not using Coq, what are you using now? I see you're verifying Tezos (if I recall, a crypto-currency competitor to Ethereum?), so I'm curious what is being used for such a task. I know for Ethereum, the K framework has been used (but I'm starting to believe that Coq could've done just a fine job).

**Comment by clarus** [comment]
> Ah ok. I'll do that then.

:+1: 

> If you are not using Coq, what are you using now? I see you're verifying Tezos (if I recall, a crypto-currency competitor to Ethereum?), so I'm curious what is being used for such a task. I know for Ethereum, the K framework has been used (but I'm starting to believe that Coq could've done just a fine job).

I am currently working on https://github.com/clarus/coq-of-ocaml to translate OCaml programs to Coq. In particular we aim to translate the Tezos implementation which is written in OCaml to Coq: https://gitlab.com/nomadic-labs/coq-tezos-of-ocaml Tezos is indeed a competitor to Ethereum.

I think that what people did in Ethereum with the K framework was to verify smart-contracts. What we want to do with coq-of-ocaml is to verify the implementation of Tezos (including the interpreter of smart-contracts and the consensus protocol). There is a project to verify smart-contracts of Tezos with K too I think. We also have https://gitlab.com/nomadic-labs/mi-cho-coq which is a Coq library to verify smart-contracts in Coq.

**Comment by lf94** [comment]
Yes it's to used to verify smart contracts, but in order to verify smart contracts they had to first verify the EVM, and created K-EVM.

Very cool the approach Tezos is taking though. Will both implementations live side-by-side (always transpiling to Coq for testing) or is the goal a Coq-only source code?

Thank you for your responses, I greatly appreciate it. I find it difficult to find others doing software verification with Coq in a realistic setting. I'll check out those projects you're working on!

**Comment by clarus** [comment]
> Yes it's to used to verify smart contracts, but in order to verify smart contracts they had to first verify the EVM, and created K-EVM.

It seems to me that they created an alternative implementation of the EVM with K-EVM. Thus they formalized the semantics of the EVM, probably verified some properties but did not verify the official EVM implementation.

> Very cool the approach Tezos is taking though. Will both implementations live side-by-side (always transpiling to Coq for testing) or is the goal a Coq-only source code?

The goal is to keep the source code in OCaml, so that more developers can understand it. This also offer a simpler language, in the sense it is only possible to do programming rather than programming + dependent types + proofs. Also I think that Coq is less stable than OCaml.

> Thank you for your responses, I greatly appreciate it. I find it difficult to find others doing software verification with Coq in a realistic setting. I'll check out those projects you're working on!

:ok_hand:
